### ISSUE TITLE
Cannot go on after shows Figure 1

### ISSUE THREAD

**Issue by Sandman6z** [lwang8797/HeatBeatClassification#2]
The program is stuck after the Figure 1 appears.
As it happens, after I turned off the Figure image but didn't close Powershell.
I found that the program contiuned to run and training results came out.

---
Please find out which snippet of code is affecting the program.

**Comment by lwang8797** [comment]
thx, I haven't found this bug because I use the SPYDER toolkit,  let's find out the bug~
